### Assignment 3 -- Hypothesis Testing

#### Q1.

A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.
Dataset --> Cutlets.csv

In [1]:
#Loading the Required Libaries
import pandas as pd
import scipy 
import numpy as np
from scipy import stats

In [2]:
#Loading the Dataset
cutlet = pd.read_csv("C:/Users/Akaash/Downloads/Cutlets.csv")
cutlet.head(3)

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300

Defining the Hypothesis,

H0: μ1 = μ2 (No Difference in the Diameter)

H1: μ1 ≠ μ2 (There is Difference in the Diameter)

In [3]:
#Formula of P_value for Two Sample test 
p_value = stats.ttest_ind(cutlet["Unit A"],cutlet["Unit B"])

In [4]:
#Getting the  result using if conditions
α = 0.05  # Standard
if p_value[1] < α:
    print("The p_value is:",p_value[1],",Which is less then α, Reject H0, which means There is Difference in the Diameter")
else:
    print("The p_value is:",p_value[1],",Which is greater then α, Fail to Reject H0, which means No Difference in the Diameter")

The p_value is: 0.4722394724599501 ,Which is greater then α, Fail to Reject H0, which means No Difference in the Diameter


#### Q2.

A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
   
Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.

Dataset --> LabTAT.csv

In [5]:
#Loading the Dataset
TAT = pd.read_csv("C:/Users/Akaash/Downloads/LabTAT.csv")
TAT.head(3)

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18

It is a Anova Test as more than 2 features are been compared Simultanously So,

Defining the Hypothesis,

H0: μ1 = μ2 = μ3 = μ4 (No Difference in Average TAT)

H1: μ1 = μ2 = μ3 ≠ μ  (There is Difference in Average TAT)

In [6]:
##Formula of Anova Test -- Gives Two Value t-statistic and p_value

p_value = stats.f_oneway(TAT["Laboratory 1"],TAT["Laboratory 2"],TAT["Laboratory 3"],TAT["Laboratory 4"])

In [7]:
#Getting the using if conditions
α = 0.05  # Standard
if p_value[1] < α:
    print("The p_value is:",p_value[1],",Which is less then α, Reject H0, which means Atleast One is Different")
else:
    print("The p_value is:",p_value[1],",Which is greater then α, Fail to Reject H0, No Difference")

The p_value is: 2.1156708949992414e-57 ,Which is less then α, Reject H0, which means Atleast One is Different


#### Q3.

Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

Dataset --> BuyerRatio.csv

In [8]:
#Loading the Dataset
buyer = pd.read_csv("C:/Users/Akaash/Downloads/BuyerRatio.csv")
buyer

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

It is Chi Square Test As it need to check the proportion betweem features

So Hypothesis is

H0:All Proportion are equal 

H1:Not all Proportion are equal

In [9]:
#libary for chi square 
from scipy.stats import chi2_contingency

In [10]:
#Taking data into array for observed Value
Observed_Values = np.array([[50,142,31,70],[435,1523,1356,750]])
Observed_Values

array([[  50,  142,   31,   70],
       [ 435, 1523, 1356,  750]])

In [11]:
#To get the Expected Value : 

# Using stats.chi2_contingency(crosstab) : this gives,chi square statistic,p_value & Expected value for observation
val=stats.chi2_contingency(Observed_Values)

#chi square statistic,p_value & Expected value of Observed_values
val

(67.43519606413847,
 1.5111907470393948e-14,
 3,
 array([[  32.61533165,  111.96809731,   93.27312371,   55.14344733],
        [ 452.38466835, 1553.03190269, 1293.72687629,  764.85655267]]))

In [12]:
#Getting Expected Value from 'val' 
Expected_Values=val[3]
Expected_Values

array([[  32.61533165,  111.96809731,   93.27312371,   55.14344733],
       [ 452.38466835, 1553.03190269, 1293.72687629,  764.85655267]])

In [13]:
#Calculating Degree of Freedom
no_of_rows=len(buyer.iloc[0:2,0])
no_of_columns=len(buyer.iloc[0,0:4])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:",ddof)
alpha = 0.05

Degree of Freedom: 3


In [14]:
#Calculating chi-square statistic for expected value
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [15]:
#Printing value
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 18.570327437743096


In [16]:
#calculating critical value
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 7.814727903251179


In [17]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)

p-value: 0.00033542182749746186
Significance level:  0.05
Degree of Freedom:  3


In [18]:
if chi_square_statistic>=critical_value:
    print("Reject H0,Not All Proportions are Equal")
else:
    print("Fail to Reject H0,All Proportions are Equal")
    
if p_value<=alpha:
    print("Reject H0,Not All Proportions are Equal")
else:
    print("Fail to Reject H0,All Proportions are Equal")

Reject H0,Not All Proportions are Equal
Reject H0,Not All Proportions are Equal


#### Q4.

TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences

Dataset-->CustomerOrderForm.csv

In [19]:
#Loading the Dataset
Cus = pd.read_csv("C:/Users/Akaash/Downloads/CustomerOrderForm.csv")
Cus.head(3)

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free

It is Chi Square Test As it all the data in the dataset is Categorical

So Hypothesis is

H0:Defective Varies By Centre 

H1:Defective Not Varies By Centre

In [20]:
Cus.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [21]:
Cus.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [22]:
Cus.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [23]:
Cus.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [24]:
#Taking data into array for observed Value
Observed_Values = np.array([[271,267,269,280],[29,33,31,20]])
Observed_Values

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [25]:
#To get the Expected Value : 

# Using stats.chi2_contingency(crosstab) : this gives,chi square statistic,p_value & Expected value for observation
val=stats.chi2_contingency(Observed_Values)

#chi square statistic,p_value & Expected value of Observed_values
val

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [26]:
#Getting Expected Value from 'val' 
Expected_Values=val[3]
Expected_Values

array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]])

In [27]:
#Calculating Degree of Freedom
no_of_rows=len(buyer.iloc[0:2,0])
no_of_columns=len(buyer.iloc[0,0:4])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:",ddof)
alpha = 0.05

Degree of Freedom: 3


In [28]:
#Calculating chi-square statistic for expected value
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [29]:
#Printing value
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 0.9036806669326146


In [30]:
#calculating critical value
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 7.814727903251179


In [31]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)

p-value: 0.8245394896914965
Significance level:  0.05
Degree of Freedom:  3


In [32]:
if chi_square_statistic>=critical_value:
    print("Reject H0, Defective Not Varies By Centre")
else:
    print("Fail to Reject H0, Defective Varies By Centre")
    
if p_value<=alpha:
    print("Reject H0, Defective Not Varies By Centre")
else:
    print("Fail to Reject H0, Defective Varies By Centre")

Fail to Reject H0, Defective Varies By Centre
Fail to Reject H0, Defective Varies By Centre
